apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: kube-registry
data:
  config.yml: |+
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
        cache:
            layerinfo: inmemory
            blobdescriptor: inmemory
        filesystem:
            rootdirectory: /var/lib/registry
        maintenance:
          uploadpurging:
              enabled: false
        delete:
          enabled: true
    http:
        addr: :443
        secert: placeholder
        host: https://hub.hiecho.cn
        debug:
            addr: :5001
        tls:
            certificate: /etc/registry/domain.crt
            key: /etc/registry/domain.key
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/authpasswd

  authpasswd:
    rongbochen:$2y$05$CMJvP.33BbbbbRZ1Yglse8JX/.PCbvLhjEADBpeI1HXkF.zXvTO.
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: kube-registry
  labels:
    app: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        k8s_cluster: kube-registry
      containers:
        - name: registry
          image: "registry.cn-hangzhou.aliyuncs.com/hikubernetes/registry:2.6.2"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/registry
          - serve
          - /etc/docker/registry/config.yml
          ports:
            - containerPort: 443
              hostPort: 443
              name: porthttps
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry/
            - name: registry-config
              mountPath: /etc/docker/registry
            - name: tls-registry
              mountPath: /etc/registry
      volumes:
        - name: registry-config
          configMap:
            name: registry-config
        - name: data
          hostPath:
            path: /Docker
        - name: tls-registry
          configMap:
            name: tls-registry
---

apiVersion: v1
kind: ConfigMap
data:
  domain.crt: "-----BEGIN CERTIFICATE-----\r\nMIIFmjCCBIKgAwIBAgIQDg7v+JFrkKoYfWPBApaokjANBgkqhkiG9w0BAQsFADBy\r\nMQswCQYDVQQGEwJDTjElMCMGA1UEChMcVHJ1c3RBc2lhIFRlY2hub2xvZ2llcywg\r\nSW5jLjEdMBsGA1UECxMURG9tYWluIFZhbGlkYXRlZCBTU0wxHTAbBgNVBAMTFFRy\r\ndXN0QXNpYSBUTFMgUlNBIENBMB4XDTIwMDQwNzAwMDAwMFoXDTIxMDQwODEyMDAw\r\nMFowGDEWMBQGA1UEAxMNaHViLmhpZWNoby5jbjCCASIwDQYJKoZIhvcNAQEBBQAD\r\nggEPADCCAQoCggEBANoX/7mF+W2+BE9p4uUTMLhX176mdlA2oo9SFkw13m041nfu\r\nao0RADMVF/ELkIxa+MBRHaeX/DO2eIiD61RNoGn+chLNQ6wLJVMcV0WBOLmY7jGy\r\nz4i80CFj176kBAEpIfUXZ3Z5lexHKAI5uJuAhL4h+Kk1NXLNtxH1RAgt0W17KeEH\r\nZUavzT3tyDhwfIB/yO0Z6sGq+wbzsYzBsK7p5OnZIVJMoI8H4PksmpgBBoEJFrZw\r\n/oJ5LVchkK9eTUw01JI5UoOhWz7AodRxnOQsyP+bZHbk+RaKtV4IB60pHirtntf3\r\n5v8jmj86MVLxLLSP5JyyWMy7O5yiz6scZ1bPfK8CAwEAAaOCAoQwggKAMB8GA1Ud\r\nIwQYMBaAFH/TmfOgRw4xAFZWIo63zJ7dygGKMB0GA1UdDgQWBBQWO/+LQObc3vbN\r\n7yTaQRWyTWaMvzAYBgNVHREEETAPgg1odWIuaGllY2hvLmNuMA4GA1UdDwEB/wQE\r\nAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwTAYDVR0gBEUwQzA3\r\nBglghkgBhv1sAQIwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQu\r\nY29tL0NQUzAIBgZngQwBAgEwgZIGCCsGAQUFBwEBBIGFMIGCMDQGCCsGAQUFBzAB\r\nhihodHRwOi8vc3RhdHVzZS5kaWdpdGFsY2VydHZhbGlkYXRpb24uY29tMEoGCCsG\r\nAQUFBzAChj5odHRwOi8vY2FjZXJ0cy5kaWdpdGFsY2VydHZhbGlkYXRpb24uY29t\r\nL1RydXN0QXNpYVRMU1JTQUNBLmNydDAJBgNVHRMEAjAAMIIBBQYKKwYBBAHWeQIE\r\nAgSB9gSB8wDxAHcA9lyUL9F3MCIUVBgIMJRWjuNNExkzv98MLyALzE7xZOMAAAFx\r\nU+06+gAABAMASDBGAiEAt5Ee4gEQPlEWdfIMSTmx2fwbpxW3kV8diasaeAY1XHsC\r\nIQCwjAArpNZo/PAxfYfi3+II9kbYpG/J1db8VfRk+sz8gQB2AFzcQ5L+5qtFRLFe\r\nmtRW5hA3+9X6R9yhc5SyXub2xw7KAAABcVPtOzgAAAQDAEcwRQIgfHmfSEWdocPt\r\nFNiAg2qB0XXSbMQslTYrrjpentRL8E0CIQDZOgPMpVnezosnBSe/xa9ZbeGL2SqD\r\nVhRQR8MO4Enh7DANBgkqhkiG9w0BAQsFAAOCAQEAPk4apF3VX5+8UqAsqfXt51/H\r\nGoQLPcbpVVZTYZYpXZtAf2k/xUwiSKsna3iaSw6qbZxUqgm9JIoOXLLv1HanYR1Y\r\nfWQJg9CT4Qo2BcN7QDHGE8JcWOWvUhwX/Wz5Cjf7q0Ptw17FJq7hv3zbd+L3CTwe\r\nwHZ2QXU7Q9T8IEea0L9R5JPB0c8zevZtfoQAESyzmy2jle7EmtZ6iUt+U1smx5+O\r\nRf5HU+paNnBbHN3Uv8rmWXyPhaNRxcwHUM7jvApvLdOKG4hfaOZikUhFo5wG4RhK\r\nn7/rLgJYlZAeA07gcOCWm6ubdc9V7JptAikQxdI+GvzoWsSevQtRmHJbPI/dbA==\r\n-----END CERTIFICATE-----"
  domain.key: "-----BEGIN RSA PRIVATE KEY-----\r\nMIIEogIBAAKCAQEA2hf/uYX5bb4ET2ni5RMwuFfXvqZ2UDaij1IWTDXebTjWd+5q\r\njREAMxUX8QuQjFr4wFEdp5f8M7Z4iIPrVE2gaf5yEs1DrAslUxxXRYE4uZjuMbLP\r\niLzQIWPXvqQEASkh9RdndnmV7EcoAjm4m4CEviH4qTU1cs23EfVECC3RbXsp4Qdl\r\nRq/NPe3IOHB8gH/I7Rnqwar7BvOxjMGwrunk6dkhUkygjwfg+SyamAEGgQkWtnD+\r\ngnktVyGQr15NTDTUkjlSg6FbPsCh1HGc5CzI/5tkduT5Foq1XggHrSkeKu2e1/fm\r\n/yOaPzoxUvEstI/knLJYzLs7nKLPqxxnVs98rwIDAQABAoIBACQoxiI1LMmTBMrt\r\nOYxqdfGdGtebaNKxeZqn7QDTY56Z8FvFFeRv9P0DL8uBc9oEJpRYPpbwCNrCvlGV\r\nXFnyCY6D/IIn3I2fRsp0pfbk+bSH6bd9YpGqCxtQyaSW3qpvQ+02EADhdXJ4dREy\r\nucFfzw0Tu9MYz9T0zOK3gVaWe3pvmoBP8LHU/6I9UnNl7lLKTt0SG8CFMENqU/EH\r\nQzzjbXsWLiDTrVRK2PXIXLdemtQ6CxmacwnFZbZkVB8v9/68bgUjNsw7rObtBhRx\r\nlM4VHQ2MwaYHLtloccYDyEk1w4xsbbCvUqoLc+y1QMxVIUfH0Jbco3up2Ad0H8Pl\r\noabJBfUCgYEA/N3JtCNgqKQWCgd4OhwRRw7ZgUc8cWwf5j6JLOxCpr8SQZ0GAqps\r\ndcghpscWf3ovjrYL6P8Wn1n3Qi9OVAKk2zy+a9CX54AH2tYPj6OCqUJ2u6u3eXAu\r\n/+hfFBFNIrjvhnfkMscyPJmrTnOL+3p1RcdpPs0CsrNiO4UdxrWbUJMCgYEA3Mvl\r\nUmJ2GrQ7KHk4NT6XUEz0Cc8517Y+xKg6LmIFiIzFcIIcoghN6G4VU6Qq/rVHpLbC\r\ntF6qB0sCwLsgGq3P9ges26GcZqy0OORLVX/q3irR5VwlnOHADwo6g7LWSk/r2WN/\r\nLklV1Kcc4/1ejLN8vE58LPYq2QYuMVhCM1kjIPUCgYB4MTfBzxsPrcboB3rnLBYu\r\nT2mlYGXjh8B14X20g6x+s82KsId91uHs7i7IplMUTtCyJeftXOq03b+AjxnNJuCT\r\ncQEWIDVEDYAuTZdh8BeYOoZTWCDCsUc1zo766+pdOchogy5N0I8ZbPWXOabs5t09\r\nSLbG6g2BQXDM1846eHIVzwKBgDUIMCtqhM2DLpZZDzwSrYtXAGJ+yHjcSBU6Bsdv\r\nOb8DeMS+K5xrfDLwheTSEJWe+vdAAmIKPrKDvMSH7X0a9FE2pLkYBxXOM3dathFy\r\nKPp1tHZvfIVC37t9DHLneHre2VocgMagTKJIBTNpftUyoyoje8Xc1ovL5Tpq5XOp\r\n3DslAoGAbNWgkTfLJ98ITUZfaroYjvPFxXPE20TK4i06LDRKBvzaYP8wpX01jSBM\r\nsUtCaZ86D2zfTyvcnmfILO/sF5NVxubQD2gngyyt1YHi7ZWGYdroqKiAhSmRj/ov\r\n5lXAf4jAFKH5YNNUU8g4MnK/7Ha4PaxIfeLcC5xxJmjHwUBaVe8=\r\n-----END RSA PRIVATE KEY-----"
metadata:
  name: tls-registry
  namespace: kube-registry

